### ISSUE TITLE
cljs chrome-headless advanced test failing on linux

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#28]
```
testing ClojureScript source under chrome-headless, cljs optimizations: advanced
HeadlessChrome 79.0.3945 (Linux 0.0.0) ERROR
  Uncaught TypeError: XR.O is not a function
  at target/cljsbuild/test/chrome-headless-advanced/compiled.js:1219:338

  TypeError: XR.O is not a function
      at target/cljsbuild/test/chrome-headless-advanced/compiled.js:1219:338
```

This works under macOS and worked for older versions of Chrome on Linux.

On CircleCI linux docker image (where we are failing):
```
$ /opt/google/chrome/chrome --version
Google Chrome 79.0.3945.79 unknown
```

On macOS dev box:
```
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 79.0.3945.79
```

**Comment by lread** [comment]
Suspicious things I am doing: 
- setting cljs compiler option to nil to allow for namespace support for ns auto-resolve tests

Trials & Observations (unless otherwise noted, cljs compiler opts `:output-dir` and `:output-to` deleted before run)
- run each test namespace individually and all passes.
- run all tests fails as described
- rerun same without deleting `:output-dir` and `:output-to`, it passes.
- rerun same, it fails as described
- Tried to diagnose with cljs compiler opts `:pseudo-names true` and `:pretty-print true` as per [cljs advanced faq](https://clojurescript.org/reference/advanced-compilation#fixing-advanced-compilation-issues) but this caused tests to pass
- run with auto-resolve ns tests commented out and it passes

I think I'll pause this and move onto #7 - its resolution might make this problem go away.

**Comment by lread** [comment]
Test has been re-enabled, and is now skipping namespace tests.
