### ISSUE TITLE
Investigate why sci native-image test is failing for tools.reader 1.3.3

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#57]
**Version**
Current HEAD 337d69c77106a66e5dd534580a87d91d42bdc22b at time of this writing.

**Platform**
Operating System: macOS 10.15.6
Clojure version: 1.10.1.561
JDK vendor and version: GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)

**Symptom**
When attempting to upgrade [tools.reader](https://github.com/clojure/tools.reader) from 1.3.2 to 1.3.3, Graal `native-image` fails.

**Reproduction**
At command prompt, run:
```
./script/sci_native_test.clj
```

**Actual behavior**
GraalVM `native-image` fails with 
```
VMError$HostedError: clojure.tools.reader$read.invokeStatic(Object, Object): has no code address offset set
```

Full output from script:
```
  Creating native image for testing via sci  
java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

native-image max memory: 6g

  Locate GraalVM native-image  
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Component Native Image (org.graalvm.native-image) is already installed.
found: /Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/bin/native-image

  Clean  
all clean

  Expose rewrite-cljc API to sci  
Generated: target/generated/sci-test/src/lib_under_sci_test.clj

  Compute classpath  
JDK major version seems to be 11; including reflection fixes.

Classpath:
- target/generated/sci-test/src
- src
- /Users/lee/.m2/repository/org/clojure/clojure/1.10.2-alpha1/clojure-1.10.2-alpha1.jar
- /Users/lee/.m2/repository/borkdude/clj-reflector-graal-java11-fix/0.0.1-graalvm-20.2.0/clj-reflector-graal-java11-fix-0.0.1-graalvm-20.2.0.jar
- /Users/lee/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar
- /Users/lee/.m2/repository/org/clojure/spec.alpha/0.2.187/spec.alpha-0.2.187.jar
- /Users/lee/.m2/repository/org/clojure/tools.namespace/1.0.0/tools.namespace-1.0.0.jar
- /Users/lee/.m2/repository/org/clojure/java.classpath/1.0.0/java.classpath-1.0.0.jar
- /Users/lee/.m2/repository/borkdude/edamame/0.0.11-alpha.13/edamame-0.0.11-alpha.13.jar
- /Users/lee/.m2/repository/org/clojure/tools.reader/1.3.3/tools.reader-1.3.3.jar
- /Users/lee/.gitlibs/libs/lread/sci-test/345e904ccff060e6aad7d630e0002a6f1a707947/src
- /Users/lee/.m2/repository/org/clojure/test.check/1.0.0/test.check-1.0.0.jar
- /Users/lee/.m2/repository/borkdude/sci.impl.reflector/0.0.1-java11/sci.impl.reflector-0.0.1-java11.jar
- /Users/lee/.gitlibs/libs/borkdude/sci/b1ab8290291e41f99fc236e76f5d6a3ba447547e/resources
- /Users/lee/.gitlibs/libs/borkdude/sci/b1ab8290291e41f99fc236e76f5d6a3ba447547e/src

Deps tree:
org.clojure/clojure 1.10.2-alpha1
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.187
borkdude/clj-reflector-graal-java11-fix 0.0.1-graalvm-20.2.0
org.clojure/tools.reader 1.3.3
lread/sci-test https://github.com/lread/sci-test.git 345e904
  org.clojure/tools.namespace 1.0.0
    org.clojure/java.classpath 1.0.0
  org.clojure/test.check 1.0.0
  borkdude/sci https://github.com/lread/sci.git b1ab829
    borkdude/edamame 0.0.11-alpha.13
borkdude/sci.impl.reflector 0.0.1-java11

  AOT compile sources  
sci-test.main

  Generate reflection file for Graal native-image  
target/native-image/reflection.json

  Graal native-image compile AOT  
Executing [
/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.2.0 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/truffle/truffle-api.jar \
-javaagent:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dclojure.spec.skip-macros=true \
-Dclojure.compiler.direct-linking=true \
-Xmx6g \
-cp \
/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/svm.jar:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/objectfile.jar:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/javacpp-shadowed.jar:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/svm-llvm.jar:/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/library-support.jar:/Users/lee/proj/oss/rewrite-cljs-playground/target/generated/sci-test/src:/Users/lee/proj/oss/rewrite-cljs-playground/src:/Users/lee/.m2/repository/org/clojure/clojure/1.10.2-alpha1/clojure-1.10.2-alpha1.jar:/Users/lee/.m2/repository/borkdude/clj-reflector-graal-java11-fix/0.0.1-graalvm-20.2.0/clj-reflector-graal-java11-fix-0.0.1-graalvm-20.2.0.jar:/Users/lee/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar:/Users/lee/.m2/repository/org/clojure/spec.alpha/0.2.187/spec.alpha-0.2.187.jar:/Users/lee/.m2/repository/org/clojure/tools.namespace/1.0.0/tools.namespace-1.0.0.jar:/Users/lee/.m2/repository/org/clojure/java.classpath/1.0.0/java.classpath-1.0.0.jar:/Users/lee/.m2/repository/borkdude/edamame/0.0.11-alpha.13/edamame-0.0.11-alpha.13.jar:/Users/lee/.m2/repository/org/clojure/tools.reader/1.3.3/tools.reader-1.3.3.jar:/Users/lee/.gitlibs/libs/lread/sci-test/345e904ccff060e6aad7d630e0002a6f1a707947/src:/Users/lee/.m2/repository/org/clojure/test.check/1.0.0/test.check-1.0.0.jar:/Users/lee/.m2/repository/borkdude/sci.impl.reflector/0.0.1-java11/sci.impl.reflector-0.0.1-java11.jar:/Users/lee/.gitlibs/libs/borkdude/sci/b1ab8290291e41f99fc236e76f5d6a3ba447547e/resources:/Users/lee/.gitlibs/libs/borkdude/sci/b1ab8290291e41f99fc236e76f5d6a3ba447547e/src:/Users/lee/proj/oss/rewrite-cljs-playground/classes \
-H:Path=/Users/lee/proj/oss/rewrite-cljs-playground \
-H:Name=target/sci-test-rewrite-cljc \
-H:+ReportExceptionStackTraces \
'-H:ClassInitialization=java.lang.Math$RandomNumberGeneratorHolder:run_time' \
-H:ClassInitialization=:build_time \
-H:Log=registerResource: \
-H:+EnableAllSecurityServices \
-H:FallbackThreshold=0 \
-H:+ReportUnsupportedElementsAtRuntime \
-H:CLibraryPath=/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/lib/svm/clibraries/darwin-amd64 \
-H:ReflectionConfigurationFiles=/Users/lee/proj/oss/rewrite-cljs-playground/target/native-image/reflection.json \
-H:Class=sci_test.main \

]
[target/sci-test-rewrite-cljc:42917]    classlist:   3,633.44 ms,  0.96 GB
[target/sci-test-rewrite-cljc:42917]        (cap):   2,729.47 ms,  0.96 GB
[target/sci-test-rewrite-cljc:42917]        setup:   4,603.32 ms,  0.96 GB
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[thread:29] scope: ForkJoinPool-4-worker-3
  [thread:29] scope: ForkJoinPool-4-worker-3.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/java.nio.file.spi.FileSystemProvider
  [thread:29] scope: ForkJoinPool-4-worker-3.registerResource
  Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
[target/sci-test-rewrite-cljc:42917]     (clinit):     388.03 ms,  2.65 GB
[target/sci-test-rewrite-cljc:42917]   (typeflow):  14,424.70 ms,  2.65 GB
[target/sci-test-rewrite-cljc:42917]    (objects):  38,580.96 ms,  2.65 GB
[target/sci-test-rewrite-cljc:42917]   (features):   1,995.20 ms,  2.65 GB
[target/sci-test-rewrite-cljc:42917]     analysis:  57,650.69 ms,  2.65 GB
[target/sci-test-rewrite-cljc:42917]     universe:   1,358.51 ms,  2.65 GB
[target/sci-test-rewrite-cljc:42917]      (parse):   5,284.47 ms,  2.83 GB
[target/sci-test-rewrite-cljc:42917]     (inline):   4,270.39 ms,  3.44 GB
[target/sci-test-rewrite-cljc:42917]    (compile):  30,895.11 ms,  3.67 GB
[target/sci-test-rewrite-cljc:42917]      compile:  45,362.98 ms,  3.67 GB
[target/sci-test-rewrite-cljc:42917]        image:   2,054.04 ms,  3.67 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.VMError$HostedError: clojure.tools.reader$read.invokeStatic(Object, Object): has no code address offset set.
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:661)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.svm.core.util.VMError$HostedError: clojure.tools.reader$read.invokeStatic(Object, Object): has no code address offset set.
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.hosted.meta.HostedMethod.getCodeAddressOffset(HostedMethod.java:149)
	at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.patchMethods(LIRNativeImageCodeCache.java:161)
	at com.oracle.svm.hosted.image.NativeBootImage$NativeTextSectionImpl.writeTextSection(NativeBootImage.java:910)
	at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:447)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:650)
	... 7 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
      116.19 real       646.02 user         9.12 sys
4643414016  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
   1273220  page reclaims
      2182  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
      3923  signals received
      7947  voluntary context switches
    726989  involuntary context switches

* error: shell exited with 1 for:
 ("/usr/bin/time"
 "-l"
 "/Users/lee/.sdkman/candidates/java/20.2.0.r11-grl/bin/native-image"
 "-H:Name=target/sci-test-rewrite-cljc"
 "-H:+ReportExceptionStackTraces"
 "-J-Dclojure.spec.skip-macros=true"
 "-J-Dclojure.compiler.direct-linking=true"
 "-H:ReflectionConfigurationFiles=target/native-image/reflection.json"
 "--initialize-at-run-time=java.lang.Math$RandomNumberGeneratorHolder"
 "--initialize-at-build-time"
 "-H:Log=registerResource:"
 "--enable-all-security-services"
 "--verbose"
 "--no-fallback"
 "--no-server"
 "--report-unsupported-elements-at-runtime"
 "-cp"
 "target/generated/sci-test/src:src:/Users/lee/.m2/repository/org/clojure/clojure/1.10.2-alpha1/clojure-1.10.2-alpha1.jar:/Users/lee/.m2/repository/borkdude/clj-reflector-graal-java11-fix/0.0.1-graalvm-20.2.0/clj-reflector-graal-java11-fix-0.0.1-graalvm-20.2.0.jar:/Users/lee/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar:/Users/lee/.m2/repository/org/clojure/spec.alpha/0.2.187/spec.alpha-0.2.187.jar:/Users/lee/.m2/repository/org/clojure/tools.namespace/1.0.0/tools.namespace-1.0.0.jar:/Users/lee/.m2/repository/org/clojure/java.classpath/1.0.0/java.classpath-1.0.0.jar:/Users/lee/.m2/repository/borkdude/edamame/0.0.11-alpha.13/edamame-0.0.11-alpha.13.jar:/Users/lee/.m2/repository/org/clojure/tools.reader/1.3.3/tools.reader-1.3.3.jar:/Users/lee/.gitlibs/libs/lread/sci-test/345e904ccff060e6aad7d630e0002a6f1a707947/src:/Users/lee/.m2/repository/org/clojure/test.check/1.0.0/test.check-1.0.0.jar:/Users/lee/.m2/repository/borkdude/sci.impl.reflector/0.0.1-java11/sci.impl.reflector-0.0.1-java11.jar:/Users/lee/.gitlibs/libs/borkdude/sci/b1ab8290291e41f99fc236e76f5d6a3ba447547e/resources:/Users/lee/.gitlibs/libs/borkdude/sci/b1ab8290291e41f99fc236e76f5d6a3ba447547e/src:classes"
 "-J-Xmx6g"
 "sci_test.main")
 *
```

**Expected behavior**
GraalVM `native-image` should successfully create executable.

**Diagnosis**
The other Graal native image test, `./script/pure_native_test.clj` does not fail.

Errant behavior for `./script/sci_native_test.clj` also occurs under GraalVM versions:
* 20.2.0 jdk8
* 20.1.0 jdk8
* 19.3.1 jdk8

It's a bit perplexing at the moment as [tools.reader has not changed that much from 1.3.2 to 1.3.3](https://github.com/clojure/tools.reader/compare/tools.reader-1.3.2...tools.reader-1.3.3).

Similar symptoms in the wild:
* https://github.com/oracle/graal/issues/1613
* https://github.com/oracle/graal/issues/2561

**Action**
Would also be interesting to see if errant behavior exhibits on Linux and Windows platforms.

This might just be a bug in GraalVM.  It might be difficult to isolate enough to report to Graal team, but worth a try.

**Comment by lread** [comment]
This will never make to master for rewrite-cljc-playground and will not be an issue for clj-commons/rewrite-clj v1.
